/**
 * Generated by scripts/compile-content.ts — do not edit.
 * Static require map for the committed Phase-7 reception clips: scored
 * listening resolves ONLY through these deterministic bundled assets,
 * never device TTS (P7 §25-26).
 */

export const RECEPTION_CLIP_ASSETS: Record<string, number> = {
};
