import { describe, expect, test } from "bun:test";
import { readFileSync } from "fs";

import { PackSchema, SourceRegistrySchema } from "../../content/schema";
import { FR_LEXEME_IDS } from "../../src/lib/learning/ids-fr";
import { audioKeyHash, checkAudio, MockTtsProvider, type AudioSpec } from "../lib/audio";
import {
  assertGeneratedTarget,
  canonicalJson,
  compileAll,
  listCourseSources,
  readJson,
  safeResolve,
  validateContent,
  validateRegistry,
} from "../lib/pipeline";

function sourcePack(courseId: string) {
  return readJson(`content/courses/${courseId}.json`);
}

/** Deep-clone with every gradeTargets field removed. */
function stripGradeTargets(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(stripGradeTargets);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value)) {
      if (k === "gradeTargets") continue;
      out[k] = stripGradeTargets(v);
    }
    return out;
  }
  return value;
}

describe("content validation (current tree)", () => {
  test("all sources, the fr map, catalog and registry validate cleanly", () => {
    const { errors } = validateContent();
    expect(errors).toEqual([]);
  });

  test("registry provenance covers every course source and the audio tree", () => {
    expect(validateRegistry().errors).toEqual([]);
  });
});

describe("schema strictness (the do-not-guess gate)", () => {
  const minimal = () => JSON.parse(JSON.stringify(sourcePack("de-en")));

  test("unknown fields are rejected, not silently dropped", () => {
    const bad = minimal();
    bad.sections[0].units[0].lessons[0].exercises[0].typo = true;
    expect(PackSchema.safeParse(bad).success).toBe(false);
  });

  test("wrong enum values and missing fields are rejected", () => {
    const bad = minimal();
    bad.sections[0].units[0].lessons[0].exercises[0].mode = "backwards";
    expect(PackSchema.safeParse(bad).success).toBe(false);
    const missing = minimal();
    delete missing.targetCode;
    expect(PackSchema.safeParse(missing).success).toBe(false);
  });

  test("a non-allowlisted license cannot be registered — DO NOT INGEST is structural", () => {
    const registry = JSON.parse(
      readFileSync(safeResolve("content/sources/registry.json"), "utf8")
    );
    registry.sources[0].license = "proprietary-unclear";
    expect(SourceRegistrySchema.safeParse(registry).success).toBe(false);
    registry.sources[0].license = "CC-BY-NC-4.0"; // NonCommercial: also not allowlisted
    expect(SourceRegistrySchema.safeParse(registry).success).toBe(false);
  });
});

describe("compiler: round-trip and determinism", () => {
  const { files, coverage } = compileAll();
  const byPath = new Map(files.map((f) => [f.relPath, f.contents]));

  test("every generated artifact matches what is committed (no drift)", () => {
    for (const f of files) {
      expect(readFileSync(safeResolve(f.relPath), "utf8")).toBe(f.contents);
    }
  });

  test("non-French packs compile byte-identical to their sources", () => {
    for (const file of listCourseSources()) {
      const courseId = file.replace(/\.json$/, "");
      if (courseId === "fr-en") continue;
      const compiled = byPath.get(`src/content/packs/${courseId}.json`);
      expect(compiled).toBe(canonicalJson(sourcePack(courseId)));
      expect(compiled!.includes("gradeTargets")).toBe(false);
    }
  });

  test("fr-en is semantically identical to its source once gradeTargets is stripped", () => {
    const compiled = JSON.parse(byPath.get("src/content/packs/fr-en.json")!);
    expect(stripGradeTargets(compiled)).toEqual(sourcePack("fr-en"));
  });

  test("compiling twice yields identical bytes (deterministic)", () => {
    const again = compileAll();
    expect(again.files).toEqual(files);
  });

  test("packs index lists all 8 courses and stays generated-only", () => {
    const index = byPath.get("src/content/packs/index.ts")!;
    expect(index.startsWith("// Generated by scripts/compile-content.ts")).toBe(true);
    for (const file of listCourseSources()) {
      expect(index).toContain(`"${file.replace(/\.json$/, "")}"`);
    }
  });

  test("gradeTargets coverage: exactly the unambiguous French exercises", () => {
    const fr = coverage["fr-en"];
    expect(fr.withGradeTargets).toBe(140);
    expect(fr.total).toBe(220);
    expect(fr.byType["select"]).toEqual({ total: 120, withGradeTargets: 120 });
    expect(fr.byType["match"]).toEqual({ total: 20, withGradeTargets: 20 });
    expect(fr.byType["wordBank"].withGradeTargets).toBe(0);
    expect(fr.byType["typeAnswer"].withGradeTargets).toBe(0);
    expect(fr.byType["fillBlank"].withGradeTargets).toBe(0);
    for (const [courseId, row] of Object.entries(coverage)) {
      if (courseId !== "fr-en") expect(row.withGradeTargets).toBe(0);
    }
  });

  test("every emitted gradeTarget is a Phase-1 lexeme id", () => {
    const known = new Set(Object.values(FR_LEXEME_IDS));
    const compiled = JSON.parse(byPath.get("src/content/packs/fr-en.json")!);
    let seen = 0;
    for (const section of compiled.sections)
      for (const unit of section.units)
        for (const lesson of unit.lessons)
          for (const e of lesson.exercises)
            for (const id of e.gradeTargets ?? []) {
              seen += 1;
              expect(known.has(id)).toBe(true);
            }
    expect(seen).toBeGreaterThanOrEqual(140);
  });

  test("the French id handoff: content source equals the runtime map", () => {
    expect(readJson("content/fr/lexemes.json")).toEqual({ ...FR_LEXEME_IDS });
  });

  test("ATTRIBUTIONS.md preserves-notices language and lists every source", () => {
    const md = byPath.get("ATTRIBUTIONS.md")!;
    expect(md).toContain("never replaces");
    expect(md).toContain("LICENSE");
    expect(md).toContain("Lingo Lessons");
    expect(md).toContain("ts-fsrs");
  });
});

describe("pipeline security", () => {
  test("safeResolve rejects traversal out of the repository", () => {
    expect(() => safeResolve("../outside.txt")).toThrow(/escapes/);
    expect(() => safeResolve("content", "../../..", "etc", "passwd")).toThrow(/escapes/);
    expect(safeResolve("content/courses")).toContain("learning-french-with-tracy");
  });

  test("writes are refused outside the declared generated targets", () => {
    expect(() => assertGeneratedTarget("src/lib/store.ts")).toThrow(/generated/);
    expect(() => assertGeneratedTarget("assets/audio/fr/x.mp3")).toThrow(/generated/);
    expect(() => assertGeneratedTarget("content/courses/fr-en.json")).toThrow(/generated/);
    expect(() => assertGeneratedTarget("src/content/packs/fr-en.json")).not.toThrow();
    expect(() => assertGeneratedTarget("ATTRIBUTIONS.md")).not.toThrow();
  });
});

describe("audio foundation", () => {
  const spec: AudioSpec = {
    language: "fr-FR",
    text: "le pain",
    voice: "fr-neutral-1",
    provider: "mock",
    rate: 1,
    pipelineVersion: 1,
  };

  test("audioKeyHash: pinned golden vector, 16 hex chars", () => {
    expect(audioKeyHash(spec)).toBe("f4a020345a9edd7b");
    expect(audioKeyHash(spec)).toMatch(/^[0-9a-f]{16}$/);
  });

  test("every spec field changes the key (cache-invalidation contract)", () => {
    const base = audioKeyHash(spec);
    expect(audioKeyHash({ ...spec, text: "le pain " })).not.toBe(base);
    expect(audioKeyHash({ ...spec, language: "fr-CA" })).not.toBe(base);
    expect(audioKeyHash({ ...spec, voice: "fr-neutral-2" })).not.toBe(base);
    expect(audioKeyHash({ ...spec, provider: "other" })).not.toBe(base);
    expect(audioKeyHash({ ...spec, rate: 0.8 })).not.toBe(base);
    expect(audioKeyHash({ ...spec, pipelineVersion: 2 })).not.toBe(base);
  });

  test("MockTtsProvider is deterministic and spec-sensitive (never networked)", async () => {
    const provider = new MockTtsProvider();
    const a = await provider.synthesize(spec);
    const b = await provider.synthesize(spec);
    expect(a.bytes).toEqual(b.bytes);
    expect(Array.from(a.bytes.slice(0, 4))).toEqual([172, 194, 126, 215]);
    const other = await provider.synthesize({ ...spec, text: "l'eau" });
    expect(other.bytes).not.toEqual(a.bytes);
  });

  test("the legacy baseline verifies: 859 untouched files + immutable manifest", () => {
    const result = checkAudio();
    expect(result.errors).toEqual([]);
    expect(result.checkedFiles).toBe(859);
  });
});
