// Generated by scripts/compile-content.ts — do not edit.
/**
 * Versioned lexicon database asset. The filename embeds the content hash,
 * so a content change ships as a NEW asset name — a previously copied
 * database is never overwritten in place. Import this module only from
 * native-only code paths (the web bundle must not pull the asset).
 */
export const FR_LEXICON_DB_NAME = "fr-lexicon-v2-51e6c8dbf48cf10b.db";
export const FR_LEXICON_CONTENT_HASH = "51e6c8dbf48cf10b";
export const FR_LEXICON_DB_ASSET = require("../../../assets/lexicon/fr-lexicon-v2-51e6c8dbf48cf10b.db");
